GET localhost:8080/auth/status
Cookie: SESSION=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwiZW1haWwiOiJ0ZXN0QGR1dHkucGFyayIsIm5hbWUiOiLrsJXshLjtmIQiLCJkZXBhcnRtZW50SWQiOjEsImRlcGFydG1lbnROYW1lIjoi7LyA7J2167aAIiwiZXhwIjoxNjczNzY3OTI0fQ.QbUr9N0ifTojo2rdaZnrlPq9clwAZAsCza2wCTdl4wo;
