= DutyPark API
DutyPark Server REST API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== Member

=== Calendar Visibility

operation::members/update-visibility[]

== Schedules

=== Create

operation::schedules/create[]

==== Create [Unauthorized]

operation::schedules/create-unauthorized[]

=== Update

operation::schedules/update[]

=== Position swap

operation::schedules/position[]

=== Delete

operation::schedules/delete[]

== Holiday

=== GET

operation::holiday/get[]

=== RESET

operation::holiday/reset[]

== Friends

=== friend-info

operation::friends/friend-info[]

== TODO

=== GET

operation::todos/get-list[]

=== CREATE

operation::todos/create[]

=== UPDATE

operation::todos/update[]

=== UPDATE-POSITION

operation::todos/update-position[]

=== DELETE

operation::todos/delete[]

== Attachments

=== Create Session

operation::attachments/sessions/create[]

==== Create Session [Unauthorized]

operation::attachments/sessions/create-unauthorized[]

=== Upload File

operation::attachments/upload[]

=== Finalize Session

operation::attachments/sessions/finalize[]

=== List Attachments

operation::attachments/list[]

=== Reorder Attachments

operation::attachments/reorder[]

=== Download Attachment

operation::attachments/download[]

=== Get Thumbnail

operation::attachments/thumbnail[]

=== Delete Attachment

operation::attachments/delete[]


