package com.tistory.shanepark.dutypark.admin.domain.dto

import com.tistory.shanepark.dutypark.member.domain.enums.Visibility
import java.time.LocalDateTime

data class AdminMemberDetailDto(
    val id: Long,
    val name: String,
    val email: String?,
    val teamId: Long?,
    val teamName: String?,
    val calendarVisibility: Visibility,
    val hasProfilePhoto: Boolean,
    val profilePhotoVersion: Long,
    val serviceAdmin: Boolean,
    val teamAdmin: Boolean,
    val teamManager: Boolean,
    val auxiliaryAccount: Boolean,
    val hasPassword: Boolean,
    val authProviders: List<String>,
    val createdDate: LocalDateTime,
    val lastModifiedDate: LocalDateTime,
    val activeSessionCount: Int,
    val pushEnabledSessionCount: Int,
    val lastActiveAt: LocalDateTime?,
    val totalScheduleCount: Long,
    val upcomingScheduleCount: Long,
    val taggedScheduleCount: Long,
    val totalTodoCount: Long,
    val todoCount: Long,
    val inProgressTodoCount: Long,
    val doneTodoCount: Long,
    val overdueTodoCount: Long,
    val dueTodayTodoCount: Long,
    val friendCount: Long,
    val familyCount: Long,
    val pendingReceivedFriendRequestCount: Long,
    val pendingSentFriendRequestCount: Long,
    val managerCount: Long,
    val managedMemberCount: Long,
    val managerNames: List<String>,
    val managedMemberNames: List<String>,
    val totalNotificationCount: Long,
    val unreadNotificationCount: Long,
)
